### ISSUE TITLE
add reference to VRS Self-Attestation repo to Conformance Program

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Conformance-Program#2]
Steering summary:
VRS can now submit Self-Attestations. The repo has been created. We suggest to add the link to the Conformance Prgrm.

---
 
- [x] P&A to decide on storage location
- [x] create [repo](https://github.com/Open-Credentialing-Initiative/marketplace/tree/main/proof)
- [x] inform Messaging Team
- [ ] add ref to [Conformance Prgrm](https://open-credentialing-initiative.github.io/Conformance-Program/#self-attestation)

**Comment by rceleste125** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [x] Create Steering-level Summary of request
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [x] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)

**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [ ] Issuers 
- [ ] Wallet Solutions
- [x] PI Verification Solutions  

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [ ] Issuer Conformance Criteria
- [ ] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [x] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [ ] Business-Level (May affect business operations)
- [x] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [ ] Technical-Level (Does not affect business operations)
- [ ] OCI Internal Process or Infrastructure
