### ISSUE TITLE
update Conformance Prgrm with trusted provider links

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Conformance-Program#3]
the prgram has only placeholder text instead of hyperlink to the repos atm. since we now have those addresses, we should add them
https://open-credentialing-initiative.github.io/Conformance-Program/latest/index.html#trusted-service-provider-registries

suggest that 
- we refer to wallet criteria for issuer reg
- link to https://github.com/Open-Credentialing-Initiative/marketplace/tree/main/proof for wallets? or create dedicated file that links to the proof folder?

**Comment by rceleste125** [comment]
Team to review for discussion and attempt to approve on 2023-11-16
