### ISSUE TITLE
Requirement for signature in all Self-Attestations

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Conformance-Program#5]
# Steering: Proposal Summary 
`This is for the Steering work START approval step. Discuss the proposed work or change.`

The Confo Prgrm requires a [signature for Self-Attestaions](https://open-credentialing-initiative.github.io/Conformance-Program/latest/index.html#self-attestation). This does not seem practical in all cases, especially for wallet NFR reporting. I suggest to re-scope the requirement.

#

# Steering: Publication Summary 
`Used to present completed work to Steering for approval to publish.`
`Discuss the work that was completed in reference to the above proposal.  Include any differences from the proposal and why.`
`use [GitHub Preview](https://htmlpreview.github.io/) to show final state of documents along with pull requests (if needed).`
#

---

**Detailed Description:**
[Signature requirement](https://open-credentialing-initiative.github.io/Conformance-Program/latest/index.html#self-attestation):

> Such representations SHALL be signed by the Service Provider’s senior management and provided to the OCI Steering Committee for publication

[NFR006 and NFR007](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#non-functional-wallet-features) in the Wallet Criteria require wallets to self-report certain performance data. This does not necessarily require a document like a signed PDF because a public website-based status display constitutes a practical hands-off option. Such a website would not be signed

I suggest we specify which type of Self-Attestations require a signature, e.g. explicit assurances concerning OCI compliance but not operational reports that make no claim beyond the presented data.

---

**Triage:**
- [x] Is Issue appropriate for OCI Architecture
- [x]  Assign Size
- [x]  Assign Priority
- [x]  Assign Label (include Type of change and Steering "Review" or "FYI")
- [x]  OCI affected Artifacts Identified
- [ ]  Assign Triage - Artifact Version Target (v x.x.x Milestone)
- [ ]  Assign Triage - Interop Profile Version Target (v x.x.x Milestone)
- [ ]  Create sub-project (if needed)
 
**Affected Parties (help determine Sunrise/Sunset):**
- [ ] Trading Partners
- [x]  Issuers
- [x]  Wallet Solutions
- [x]  PI Verification Solutions

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [ ] Issuer Conformance Criteria
- [ ] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [x] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    

> _Needs Steering Consensus_

- [ ] Business-Level (May affect business operations)
- [x] OCI Governance, Policy or website feature

**- Steering/Industry Notification**

> _Does not need Steering Consensus (Steering may require a Consensus decision or futher clarification prior to issue being resolved by P&A_

- [ ] Technical-Level (Does not affect business operations)
- [ ] OCI Internal Process or Infrastructure

**Comment by rceleste125** [comment]
Team to review for discussion and attempt to approve on 2023-11-16
