### ISSUE TITLE
Timing of operational self-attestations by wallets

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Conformance-Program#6]
# Steering: Proposal Summary 
`Used to propose a change or addition to Steering.`
`This is for the Steering work START approval step. Discuss the proposed work or change.`

The Conformance Program requires wallets to submit [Self-Attestations](https://open-credentialing-initiative.github.io/Conformance-Program/latest/index.html#self-attestation) for [NFR006 & 007](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#non-functional-wallet-features). It does not specify when wallets should begin to self-report and at which cadence. P&A should define this.

#

# Steering: Publication Summary 
`Used to present completed work to Steering for approval to publish.`
`Discuss the work that was completed in reference to the above proposal.  Include any differences from the proposal and why.`
`use [GitHub Preview](https://htmlpreview.github.io/) to show final state of documents along with pull requests (if needed).`
#

---

**Detailed Description:**

---

**Triage:**
- [x] Is Issue appropriate for OCI Architecture
- [x]  Assign Size
- [x]  Assign Priority
- [x]  Assign Label (include Type of change and Steering "Review" or "FYI")
- [x]  OCI affected Artifacts Identified
- [ ]  Assign Triage - Artifact Version Target (v x.x.x Milestone)
- [ ]  Assign Triage - Interop Profile Version Target (v x.x.x Milestone)
- [ ]  Create sub-project (if needed)
 
**Affected Parties (help determine Sunrise/Sunset):**
- [ ] Trading Partners
- [ ]  Issuers
- [x]  Wallet Solutions
- [ ]  PI Verification Solutions

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [ ] Issuer Conformance Criteria
- [ ] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [x] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    

> _Needs Steering Consensus_

- [ ] Business-Level (May affect business operations)
- [x] OCI Governance, Policy or website feature

**- Steering/Industry Notification**

> _Does not need Steering Consensus (Steering may require a Consensus decision or futher clarification prior to issue being resolved by P&A_

- [ ] Technical-Level (Does not affect business operations)
- [ ] OCI Internal Process or Infrastructure

**Comment by bluesteens** [comment]
![Image](https://github.com/Open-Credentialing-Initiative/Conformance-Program/assets/34170038/56439189-625c-4df2-8ab0-e89d6e4c10ed)

**Comment by bluesteens** [comment]
graphic might fit at the end of https://open-credentialing-initiative.github.io/Conformance-Program/latest/index.html#compliance-monitoring

**Comment by rceleste125** [comment]
Team to review for discussion and attempt to approve on 2023-11-16
